spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true
    default-schema: tasklist

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
    secret: c2xkYWtmamxqc2xmam9pd2Vqd2U7Zix3O2VmbW5na2ZtbmcubXZDSk9JRU5MQUdM
    access: 3600000
    refresh: 2592000000
server:
  port: 8081
springdoc:
  override-with-generic-response: false